import {
  signInByMagic,
  checkAuth,
  getAllArtists,
  sendCodeToPersonalEmail,
  sendCodeToPlatformEmail,
  checkPersonalCode,
  spotifyLogin,
  spotifyLogout,
  getContactInfoOfOffer,
  checkIfLiked,
  likeOrDislikeLicense,
  searchArtists,
  getFavoriteLicenses,
  sendVerificationCodeToSpotifyEmail,
  sendVCodeToSpotifyEmail,
  verifySellerAccount,
  checkFollowing,
  updateFollow,
  getFollowingBuyers,
  deleteSellerAccount,
  sendEmailToCollaborators,
} from './user'
import {
  getPlayLists,
  searchByMulti,
  getMusicFromSpotify,
  getSongsOfAlbum,
  getAlbumsOfArtist,
  searchTracks,
  getGenresList,
  getGenresOfArtists,
  getAvatarPathByDisplayname,
} from './spotify'

import {
  searchLicenses,
  getGenres,
  searchListedLicensesByFilter,
  checkduplication,
  getListedLicenseBySellerId,
  getAllUnLicensesBySellerId,
  getRecentUploads,
  getAllLicenses,
  uploadLicense,
  uploadMediaSyncLicense,
  unlistLicense,
  unlistLicenseAll,
  rejectLicense,
  approveLicense,
  adjustLicense,
  getLicenseForListedId,
  getSyncData,
  getPendingListings,
  addViewer,
  getAdditionalInfo,
  getRecommendingLicenses,
  getListedLicensesByIds,
  getNextOrPreviousLicense,
} from './listedLicenses'
import {
  getPublicProfile,
  getCollectionData,
  savePublicProfile,
  updatePublicProfile,
  deleteCollection,
  removeCollection,
  updateBuyerPlatform,
  updateBuyerMailingInfo,
  updateSellerMailingInfo,
  getBuyerMailingInfo,
  getSellerMailingInfo,
  getBuyerPlatform,
  getSellerPlatform,
  getCurrentAccount,
  getPrivateProfileData,
  getPublicProfileData,
  updateUserName,
  getUserLegalName,
  getSellerData,
  updateSellerProfile,
  getDetailCountsOfProfile,
  getSocialAccounts,
  addProfileViewer,
} from './profile'
import {
  getSoldLicenses,
  getTrendingArtist,
  getTopArtist,
  getTopSellingLicense,
  getTrendingLicense,
  getMostPopularLicenses,
  getOrdersByLicenseType,
  getSaleVolumeByMonth,
  getOwnedLicense,
  getPurchasedNonExclusive,
  getPublicLicense,
  publishLicense,
  getSaleStats,
} from './soldLicenses'
import {
  markAsReadNotification,
  markAllAsReadNotification,
  createExpiredNotification,
} from './notification'

import { getLicenseReport, reportProfile } from './report'

import { searchPublicSalesDatabase } from './publicSalesDatabase'
import { uploadCSV } from './licenseChecker'
import {
  getMyOffersForBuyer,
  getMyOffersOfSeller,
  getMadeOffers,
  getReceivedOffers,
  rejectOfferBySeller,
  accpetOfferBySeller,
  placeCounterOfferBySeller,
  withdrawCounterOffer,
  editCounterOffer,
  rejectCounterOffer,
  getTotalOffers,
} from './offers'

import {
  getHistoryByListedId,
  getSaleDetails,
  getOfferDetails,
  getAllActivities,
  getAllAccounts,
} from './history'

import { createSession, unlinkBusinessAcc, reLinkBusinessAcc } from './idenfy'
import { getChangedLicenseData } from './licenseChanges'
import { getSigninHistory, logoutHistory } from './security'

export {
  signInByMagic,
  checkAuth,
  getAllArtists,
  sendCodeToPersonalEmail,
  sendCodeToPlatformEmail,
  checkPersonalCode,
  spotifyLogin,
  spotifyLogout,
  getContactInfoOfOffer,
  searchArtists,
  getFavoriteLicenses,
  sendVerificationCodeToSpotifyEmail,
  sendVCodeToSpotifyEmail,
  verifySellerAccount,
  checkFollowing,
  updateFollow,
  getFollowingBuyers,
  deleteSellerAccount,
  sendEmailToCollaborators,
  // spotify
  getPlayLists,
  searchByMulti,
  getMusicFromSpotify,
  getSongsOfAlbum,
  getAlbumsOfArtist,
  searchTracks,
  getGenresList,
  getGenresOfArtists,
  getAvatarPathByDisplayname,
  getListedLicenseBySellerId,
  getAllUnLicensesBySellerId,
  getRecentUploads,
  getAllLicenses,
  uploadLicense,
  uploadMediaSyncLicense,
  unlistLicense,
  unlistLicenseAll,
  rejectLicense,
  approveLicense,
  adjustLicense,
  getLicenseForListedId,
  getSyncData,
  getPendingListings,
  addViewer,
  getAdditionalInfo,
  getRecommendingLicenses,
  getListedLicensesByIds,
  getNextOrPreviousLicense,
  // listed Licenses
  searchLicenses,
  getGenres,
  searchListedLicensesByFilter,
  checkduplication,
  // profile
  getPublicProfile,
  getCollectionData,
  savePublicProfile,
  updatePublicProfile,
  deleteCollection,
  removeCollection,
  updateBuyerPlatform,
  updateBuyerMailingInfo,
  updateSellerMailingInfo,
  getBuyerMailingInfo,
  getSellerMailingInfo,
  getBuyerPlatform,
  getSellerPlatform,
  getCurrentAccount,
  getPrivateProfileData,
  getPublicProfileData,
  updateUserName,
  getUserLegalName,
  getSellerData,
  updateSellerProfile,
  // check if the user favorited the license
  checkIfLiked,
  // like the license
  likeOrDislikeLicense,
  // sold licenses
  getSoldLicenses,
  getTrendingArtist,
  getTopArtist,
  getTopSellingLicense,
  getTrendingLicense,
  getMostPopularLicenses,
  getOrdersByLicenseType,
  getSaleVolumeByMonth,
  getOwnedLicense,
  getPurchasedNonExclusive,
  getPublicLicense,
  publishLicense,
  getSaleStats,
  // recommendedLicense
  // notification
  markAsReadNotification,
  markAllAsReadNotification,
  createExpiredNotification,
  // report
  getLicenseReport,
  // public sales database
  searchPublicSalesDatabase,
  // license checker
  uploadCSV,
  // offers
  getMyOffersForBuyer,
  getMyOffersOfSeller,
  getMadeOffers,
  getReceivedOffers,
  rejectOfferBySeller,
  accpetOfferBySeller,
  placeCounterOfferBySeller,
  withdrawCounterOffer,
  editCounterOffer,
  rejectCounterOffer,
  getTotalOffers,
  // history
  getHistoryByListedId,
  getSaleDetails,
  getOfferDetails,
  getAllActivities,
  getAllAccounts,
  // idenfy
  createSession,
  unlinkBusinessAcc,
  reLinkBusinessAcc,
  // license change
  getChangedLicenseData,

  // report Profile
  reportProfile,
  getDetailCountsOfProfile,
  getSocialAccounts,
  addProfileViewer,
  // security
  getSigninHistory,
  logoutHistory,
}
